# make          ./nvq, with the schema compiled in
# make test     the scripted-failure suite (Linux, nvidia kernel module loaded, jq)
# make layout   nvq's NVML/CUDA declarations against NVIDIA's headers in /usr/local/cuda-*
# make release  dist/nvq-linux-<arch> + .sha256, the artifacts a GitHub release carries
# make types    clients' types generated from the schema (Python: python/src/nvq/documents.py)
VERSION ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
ARCH ?= $(shell uname -m | sed 's/x86_64/amd64/; s/aarch64/arm64/')
CFLAGS ?= -O2
WARN = -std=c11 -Wall -Wextra -Werror

nvq: src/nvq.c src/json.h src/nvml.h src/cuda.h build/schema.inc
	$(CC) $(WARN) $(CFLAGS) -Ibuild -DNVQ_VERSION='"$(VERSION)"' -o $@ src/nvq.c -ldl

# The schema as a C byte list, with od (coreutils): no xxd on minimal build images.
build/schema.inc: schema/nvq.schema.json
	mkdir -p build
	od -An -v -tx1 $< | sed 's/ \([0-9a-f][0-9a-f]\)/0x\1,/g' > $@

test: nvq
	test/run.sh

# Every layout, constant and function signature nvq declares, against each CUDA toolkit installed.
# Deprecations print and do not fail: they are next migrations, not mismatches.
TOOLKITS ?= $(wildcard /usr/local/cuda-*/include)
layout:
	@test -n "$(TOOLKITS)" || { echo "no /usr/local/cuda-*/include"; exit 1; }
	@for d in $(TOOLKITS); do \
	  $(CC) -std=c11 -Wall -Werror -Wno-error=deprecated-declarations -I$$d -fsyntax-only test/layout.c || exit 1; \
	  echo "layout ok: $$d"; done

# Always a fresh compile on this machine: never a ./nvq left by another build.
release: build/schema.inc
	mkdir -p dist
	$(CC) $(WARN) $(CFLAGS) -Ibuild -DNVQ_VERSION='"$(VERSION)"' -o dist/nvq-linux-$(ARCH) src/nvq.c -ldl
	cd dist && sha256sum nvq-linux-$(ARCH) > nvq-linux-$(ARCH).sha256

# Generated, committed, and regenerated by CI (py.yml) to prove it matches the schema. Open TypedDicts:
# readers ignore keys they do not know, as the contract says.
types: python/src/nvq/documents.py
python/src/nvq/documents.py: schema/nvq.schema.json
	uvx --from 'datamodel-code-generator[ruff]==0.83.0' datamodel-codegen --input $< --input-file-type jsonschema \
	  --output-model-type typing.TypedDict --no-use-closed-typed-dict --target-python-version 3.12 \
	  --use-schema-description --use-field-description --disable-timestamp --formatters ruff-format \
	  --output $@

clean:
	rm -rf nvq build dist

.PHONY: test layout release types clean
