// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package nvq

import "encoding/json"
import "fmt"
import "reflect"
import "regexp"

type Arch struct {
	// "8.6"
	Compute string `json:"compute"`

	// Family corresponds to the JSON schema field "family".
	Family Family `json:"family"`

	// the compile target, "sm_86"
	SM string `json:"sm"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Arch) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["compute"]; raw != nil && !ok {
		return fmt.Errorf("field compute in Arch: required")
	}
	if _, ok := raw["family"]; raw != nil && !ok {
		return fmt.Errorf("field family in Arch: required")
	}
	if _, ok := raw["sm"]; raw != nil && !ok {
		return fmt.Errorf("field sm in Arch: required")
	}
	type Plain Arch
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Arch(plain)
	return nil
}

// PCI location as the kernel prints it
type Bus string

// UnmarshalJSON implements json.Unmarshaler.
func (j *Bus) UnmarshalJSON(value []byte) error {
	type Plain Bus
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[0-9a-f]{4,8}:[0-9a-f]{2}:[0-9a-f]{2}\.[0-7]$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^[0-9a-f]{4,8}:[0-9a-f]{2}:[0-9a-f]{2}\.[0-7]$`)
	}
	*j = Bus(plain)
	return nil
}

type Card struct {
	// Bus corresponds to the JSON schema field "bus".
	Bus Bus `json:"bus"`

	// ClocksMHz corresponds to the JSON schema field "clocksMHz".
	ClocksMHz *ClocksMHz `json:"clocksMHz,omitempty,omitzero"`

	// CUDA compute capability, "8.6"
	Compute *string `json:"compute,omitempty,omitzero"`

	// energy the card used since the driver loaded, joules; the difference of two
	// readings over their interval is average power
	EnergyJ *float64 `json:"energyJ,omitempty,omitzero"`

	// with state lost or error
	Error *Code `json:"error,omitempty,omitzero"`

	// fields whose query failed, by field
	Errors Errors `json:"errors,omitempty,omitzero"`

	// target fan speed; consumer cards with fan control off report not_supported
	FanPct *int `json:"fanPct,omitempty,omitzero"`

	// position in bus order; not CUDA's or nvidia-smi's index
	Index int `json:"index"`

	// Limits corresponds to the JSON schema field "limits".
	Limits []Limit `json:"limits,omitempty,omitzero"`

	// MemoryMiB corresponds to the JSON schema field "memoryMiB".
	MemoryMiB *MemoryMiB `json:"memoryMiB,omitempty,omitzero"`

	// /dev/nvidia<minor>; -1 when the kernel did not say
	Minor int `json:"minor"`

	// Model corresponds to the JSON schema field "model".
	Model string `json:"model"`

	// the link now and at best; a riser shows here (gen 1, width 1)
	PCIe *PCIe `json:"pcie,omitempty,omitzero"`

	// Persistence corresponds to the JSON schema field "persistence".
	Persistence *bool `json:"persistence,omitempty,omitzero"`

	// PowerW corresponds to the JSON schema field "powerW".
	PowerW *PowerW `json:"powerW,omitempty,omitzero"`

	// compute processes holding the card
	Processes []Process `json:"processes,omitempty,omitzero"`

	// performance state, 0 fastest
	PState *int `json:"pstate,omitempty,omitzero"`

	// ok: NVML reaches it. lost: fell off the bus (gpu_is_lost). error: another NVML
	// failure. unknown: NVML unusable
	State State `json:"state"`

	// TempC corresponds to the JSON schema field "tempC".
	TempC *int `json:"tempC,omitempty,omitzero"`

	// fields this card does not report
	Unsupported []string `json:"unsupported,omitempty,omitzero"`

	// UtilPct corresponds to the JSON schema field "utilPct".
	UtilPct *UtilPct `json:"utilPct,omitempty,omitzero"`

	// UUID corresponds to the JSON schema field "uuid".
	UUID UUID `json:"uuid"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Card) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["bus"]; raw != nil && !ok {
		return fmt.Errorf("field bus in Card: required")
	}
	if _, ok := raw["index"]; raw != nil && !ok {
		return fmt.Errorf("field index in Card: required")
	}
	if _, ok := raw["minor"]; raw != nil && !ok {
		return fmt.Errorf("field minor in Card: required")
	}
	if _, ok := raw["model"]; raw != nil && !ok {
		return fmt.Errorf("field model in Card: required")
	}
	if _, ok := raw["state"]; raw != nil && !ok {
		return fmt.Errorf("field state in Card: required")
	}
	if _, ok := raw["uuid"]; raw != nil && !ok {
		return fmt.Errorf("field uuid in Card: required")
	}
	type Plain Card
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.Index {
		return fmt.Errorf("field %s: must be >= %v", "index", 0)
	}
	*j = Card(plain)
	return nil
}

type ClocksMHz struct {
	// Mem corresponds to the JSON schema field "mem".
	Mem int `json:"mem"`

	// SM corresponds to the JSON schema field "sm".
	SM int `json:"sm"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ClocksMHz) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["mem"]; raw != nil && !ok {
		return fmt.Errorf("field mem in ClocksMHz: required")
	}
	if _, ok := raw["sm"]; raw != nil && !ok {
		return fmt.Errorf("field sm in ClocksMHz: required")
	}
	type Plain ClocksMHz
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ClocksMHz(plain)
	return nil
}

type Code string

const CodeAlreadyInitialized Code = "already_initialized"
const CodeArgumentVersionMismatch Code = "argument_version_mismatch"
const CodeCorruptedInforom Code = "corrupted_inforom"
const CodeDeadline Code = "deadline"
const CodeDeprecated Code = "deprecated"
const CodeDriverNotLoaded Code = "driver_not_loaded"
const CodeFreqNotSupported Code = "freq_not_supported"
const CodeFunctionNotFound Code = "function_not_found"
const CodeGPUIsLost Code = "gpu_is_lost"
const CodeGPUNotFound Code = "gpu_not_found"
const CodeInUse Code = "in_use"
const CodeInsufficientPower Code = "insufficient_power"
const CodeInsufficientResources Code = "insufficient_resources"
const CodeInsufficientSize Code = "insufficient_size"
const CodeInvalidArgument Code = "invalid_argument"
const CodeInvalidState Code = "invalid_state"
const CodeIrqIssue Code = "irq_issue"
const CodeLibRmVersionMismatch Code = "lib_rm_version_mismatch"
const CodeLibraryNotFound Code = "library_not_found"
const CodeMemory Code = "memory"
const CodeNoData Code = "no_data"
const CodeNoPermission Code = "no_permission"
const CodeNotFound Code = "not_found"
const CodeNotReady Code = "not_ready"
const CodeNotSupported Code = "not_supported"
const CodeOperatingSystem Code = "operating_system"
const CodeResetRequired Code = "reset_required"
const CodeTimeout Code = "timeout"
const CodeTooManyCards Code = "too_many_cards"
const CodeUninitialized Code = "uninitialized"
const CodeUnknown Code = "unknown"
const CodeVgpuECCNotSupported Code = "vgpu_ecc_not_supported"

var enumValues_Code = []interface{}{
	"uninitialized",
	"invalid_argument",
	"not_supported",
	"no_permission",
	"already_initialized",
	"not_found",
	"insufficient_size",
	"insufficient_power",
	"driver_not_loaded",
	"timeout",
	"irq_issue",
	"library_not_found",
	"function_not_found",
	"corrupted_inforom",
	"gpu_is_lost",
	"reset_required",
	"operating_system",
	"lib_rm_version_mismatch",
	"in_use",
	"memory",
	"no_data",
	"vgpu_ecc_not_supported",
	"insufficient_resources",
	"freq_not_supported",
	"argument_version_mismatch",
	"deprecated",
	"not_ready",
	"gpu_not_found",
	"invalid_state",
	"unknown",
	"too_many_cards",
	"deadline",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Code) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Code {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Code, v)
	}
	*j = Code(v)
	return nil
}

type ComputeMode string

const ComputeModeDefault ComputeMode = "default"
const ComputeModeExclusiveProcess ComputeMode = "exclusive_process"
const ComputeModeProhibited ComputeMode = "prohibited"
const ComputeModeUnknown ComputeMode = "unknown"

var enumValues_ComputeMode = []interface{}{
	"default",
	"prohibited",
	"exclusive_process",
	"unknown",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ComputeMode) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ComputeMode {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ComputeMode, v)
	}
	*j = ComputeMode(v)
	return nil
}

type ErrorBody struct {
	// Code corresponds to the JSON schema field "code".
	Code Code `json:"code"`

	// Detail corresponds to the JSON schema field "detail".
	Detail string `json:"detail"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ErrorBody) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["code"]; raw != nil && !ok {
		return fmt.Errorf("field code in ErrorBody: required")
	}
	if _, ok := raw["detail"]; raw != nil && !ok {
		return fmt.Errorf("field detail in ErrorBody: required")
	}
	type Plain ErrorBody
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ErrorBody(plain)
	return nil
}

// The whole command failed, or (in list) NVML could not be used.
type ErrorDocument struct {
	// Error corresponds to the JSON schema field "error".
	Error ErrorBody `json:"error"`

	// NVQ corresponds to the JSON schema field "nvq".
	NVQ SchemaVersion `json:"nvq"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ErrorDocument) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["error"]; raw != nil && !ok {
		return fmt.Errorf("field error in ErrorDocument: required")
	}
	if _, ok := raw["nvq"]; raw != nil && !ok {
		return fmt.Errorf("field nvq in ErrorDocument: required")
	}
	type Plain ErrorDocument
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ErrorDocument(plain)
	return nil
}

// fields whose query failed, by field
type Errors map[string]Code

// One line of watch, told apart by "event".
type Event interface{}

// A double-bit ECC error; uuid and bus absent when NVML named a device nvq does
// not watch.
type EventECCDouble struct {
	// At corresponds to the JSON schema field "at".
	At UnixTime `json:"at"`

	// Bus corresponds to the JSON schema field "bus".
	Bus *Bus `json:"bus,omitempty,omitzero"`

	// Data corresponds to the JSON schema field "data".
	Data int `json:"data"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// NVQ corresponds to the JSON schema field "nvq".
	NVQ SchemaVersion `json:"nvq"`

	// UUID corresponds to the JSON schema field "uuid".
	UUID *UUID `json:"uuid,omitempty,omitzero"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EventECCDouble) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["at"]; raw != nil && !ok {
		return fmt.Errorf("field at in EventECCDouble: required")
	}
	if _, ok := raw["data"]; raw != nil && !ok {
		return fmt.Errorf("field data in EventECCDouble: required")
	}
	if _, ok := raw["event"]; raw != nil && !ok {
		return fmt.Errorf("field event in EventECCDouble: required")
	}
	if _, ok := raw["nvq"]; raw != nil && !ok {
		return fmt.Errorf("field nvq in EventECCDouble: required")
	}
	type Plain EventECCDouble
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Event != "ecc_double" {
		return fmt.Errorf("field %s: must be equal to %s", "event", "ecc_double")
	}
	*j = EventECCDouble(plain)
	return nil
}

// A card NVML stopped reaching, reported once.
type EventLost struct {
	// At corresponds to the JSON schema field "at".
	At UnixTime `json:"at"`

	// Bus corresponds to the JSON schema field "bus".
	Bus Bus `json:"bus"`

	// Error corresponds to the JSON schema field "error".
	Error Code `json:"error"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// NVQ corresponds to the JSON schema field "nvq".
	NVQ SchemaVersion `json:"nvq"`

	// UUID corresponds to the JSON schema field "uuid".
	UUID UUID `json:"uuid"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EventLost) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["at"]; raw != nil && !ok {
		return fmt.Errorf("field at in EventLost: required")
	}
	if _, ok := raw["bus"]; raw != nil && !ok {
		return fmt.Errorf("field bus in EventLost: required")
	}
	if _, ok := raw["error"]; raw != nil && !ok {
		return fmt.Errorf("field error in EventLost: required")
	}
	if _, ok := raw["event"]; raw != nil && !ok {
		return fmt.Errorf("field event in EventLost: required")
	}
	if _, ok := raw["nvq"]; raw != nil && !ok {
		return fmt.Errorf("field nvq in EventLost: required")
	}
	if _, ok := raw["uuid"]; raw != nil && !ok {
		return fmt.Errorf("field uuid in EventLost: required")
	}
	type Plain EventLost
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Event != "lost" {
		return fmt.Errorf("field %s: must be equal to %s", "event", "lost")
	}
	*j = EventLost(plain)
	return nil
}

// One card's readings, every --every-ms; a reading the card cannot give is absent.
type EventSample struct {
	// At corresponds to the JSON schema field "at".
	At UnixTime `json:"at"`

	// Bus corresponds to the JSON schema field "bus".
	Bus Bus `json:"bus"`

	// cumulative, as in list
	EnergyJ *float64 `json:"energyJ,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// FanPct corresponds to the JSON schema field "fanPct".
	FanPct *int `json:"fanPct,omitempty,omitzero"`

	// Limits corresponds to the JSON schema field "limits".
	Limits []Limit `json:"limits,omitempty,omitzero"`

	// NVQ corresponds to the JSON schema field "nvq".
	NVQ SchemaVersion `json:"nvq"`

	// cumulative, as in list
	PCIeReplays *int `json:"pcieReplays,omitempty,omitzero"`

	// PowerW corresponds to the JSON schema field "powerW".
	PowerW *float64 `json:"powerW,omitempty,omitzero"`

	// SMMHz corresponds to the JSON schema field "smMHz".
	SMMHz *int `json:"smMHz,omitempty,omitzero"`

	// TempC corresponds to the JSON schema field "tempC".
	TempC *int `json:"tempC,omitempty,omitzero"`

	// UtilPct corresponds to the JSON schema field "utilPct".
	UtilPct *int `json:"utilPct,omitempty,omitzero"`

	// UUID corresponds to the JSON schema field "uuid".
	UUID UUID `json:"uuid"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EventSample) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["at"]; raw != nil && !ok {
		return fmt.Errorf("field at in EventSample: required")
	}
	if _, ok := raw["bus"]; raw != nil && !ok {
		return fmt.Errorf("field bus in EventSample: required")
	}
	if _, ok := raw["event"]; raw != nil && !ok {
		return fmt.Errorf("field event in EventSample: required")
	}
	if _, ok := raw["nvq"]; raw != nil && !ok {
		return fmt.Errorf("field nvq in EventSample: required")
	}
	if _, ok := raw["uuid"]; raw != nil && !ok {
		return fmt.Errorf("field uuid in EventSample: required")
	}
	type Plain EventSample
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Event != "sample" {
		return fmt.Errorf("field %s: must be equal to %s", "event", "sample")
	}
	*j = EventSample(plain)
	return nil
}

// First line: the cards watched and the event kinds registered on each.
type EventStart struct {
	// At corresponds to the JSON schema field "at".
	At UnixTime `json:"at"`

	// Cards corresponds to the JSON schema field "cards".
	Cards []WatchCard `json:"cards"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// NVQ corresponds to the JSON schema field "nvq".
	NVQ SchemaVersion `json:"nvq"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EventStart) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["at"]; raw != nil && !ok {
		return fmt.Errorf("field at in EventStart: required")
	}
	if _, ok := raw["cards"]; raw != nil && !ok {
		return fmt.Errorf("field cards in EventStart: required")
	}
	if _, ok := raw["event"]; raw != nil && !ok {
		return fmt.Errorf("field event in EventStart: required")
	}
	if _, ok := raw["nvq"]; raw != nil && !ok {
		return fmt.Errorf("field nvq in EventStart: required")
	}
	type Plain EventStart
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Event != "start" {
		return fmt.Errorf("field %s: must be equal to %s", "event", "start")
	}
	*j = EventStart(plain)
	return nil
}

// Waiting for driver events failed; watch retries after a second.
type EventWaitError struct {
	// At corresponds to the JSON schema field "at".
	At UnixTime `json:"at"`

	// Error corresponds to the JSON schema field "error".
	Error Code `json:"error"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// NVQ corresponds to the JSON schema field "nvq".
	NVQ SchemaVersion `json:"nvq"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EventWaitError) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["at"]; raw != nil && !ok {
		return fmt.Errorf("field at in EventWaitError: required")
	}
	if _, ok := raw["error"]; raw != nil && !ok {
		return fmt.Errorf("field error in EventWaitError: required")
	}
	if _, ok := raw["event"]; raw != nil && !ok {
		return fmt.Errorf("field event in EventWaitError: required")
	}
	if _, ok := raw["nvq"]; raw != nil && !ok {
		return fmt.Errorf("field nvq in EventWaitError: required")
	}
	type Plain EventWaitError
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Event != "wait_error" {
		return fmt.Errorf("field %s: must be equal to %s", "event", "wait_error")
	}
	*j = EventWaitError(plain)
	return nil
}

// An Xid error the driver raised; uuid and bus absent when NVML named a device nvq
// does not watch.
type EventXid struct {
	// At corresponds to the JSON schema field "at".
	At UnixTime `json:"at"`

	// Bus corresponds to the JSON schema field "bus".
	Bus *Bus `json:"bus,omitempty,omitzero"`

	// Event corresponds to the JSON schema field "event".
	Event string `json:"event"`

	// NVIDIA's name for it; empty for an Xid nvq has no name for
	Meaning string `json:"meaning"`

	// NVQ corresponds to the JSON schema field "nvq".
	NVQ SchemaVersion `json:"nvq"`

	// UUID corresponds to the JSON schema field "uuid".
	UUID *UUID `json:"uuid,omitempty,omitzero"`

	// Xid corresponds to the JSON schema field "xid".
	Xid int `json:"xid"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EventXid) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["at"]; raw != nil && !ok {
		return fmt.Errorf("field at in EventXid: required")
	}
	if _, ok := raw["event"]; raw != nil && !ok {
		return fmt.Errorf("field event in EventXid: required")
	}
	if _, ok := raw["meaning"]; raw != nil && !ok {
		return fmt.Errorf("field meaning in EventXid: required")
	}
	if _, ok := raw["nvq"]; raw != nil && !ok {
		return fmt.Errorf("field nvq in EventXid: required")
	}
	if _, ok := raw["xid"]; raw != nil && !ok {
		return fmt.Errorf("field xid in EventXid: required")
	}
	type Plain EventXid
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Event != "xid" {
		return fmt.Errorf("field %s: must be equal to %s", "event", "xid")
	}
	*j = EventXid(plain)
	return nil
}

type EventsEvent string

const EventsEventECCDouble EventsEvent = "ecc_double"
const EventsEventXid EventsEvent = "xid"

var enumValues_EventsEvent = []interface{}{
	"xid",
	"ecc_double",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EventsEvent) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EventsEvent {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_EventsEvent, v)
	}
	*j = EventsEvent(v)
	return nil
}

type Family string

const FamilyAda Family = "ada"
const FamilyAmpere Family = "ampere"
const FamilyBlackwell Family = "blackwell"
const FamilyHopper Family = "hopper"
const FamilyKepler Family = "kepler"
const FamilyMaxwell Family = "maxwell"
const FamilyPascal Family = "pascal"
const FamilyTuring Family = "turing"
const FamilyUnknown Family = "unknown"
const FamilyVolta Family = "volta"

var enumValues_Family = []interface{}{
	"kepler",
	"maxwell",
	"pascal",
	"volta",
	"turing",
	"ampere",
	"ada",
	"hopper",
	"blackwell",
	"unknown",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Family) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Family {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Family, v)
	}
	*j = Family(v)
	return nil
}

type Layout struct {
	// MaxBlockDim corresponds to the JSON schema field "maxBlockDim".
	MaxBlockDim []int `json:"maxBlockDim,omitempty,omitzero"`

	// MaxBlocksPerSM corresponds to the JSON schema field "maxBlocksPerSM".
	MaxBlocksPerSM *int `json:"maxBlocksPerSM,omitempty,omitzero"`

	// MaxGridDim corresponds to the JSON schema field "maxGridDim".
	MaxGridDim []int `json:"maxGridDim,omitempty,omitzero"`

	// MaxThreadsPerBlock corresponds to the JSON schema field "maxThreadsPerBlock".
	MaxThreadsPerBlock *int `json:"maxThreadsPerBlock,omitempty,omitzero"`

	// MaxThreadsPerSM corresponds to the JSON schema field "maxThreadsPerSM".
	MaxThreadsPerSM *int `json:"maxThreadsPerSM,omitempty,omitzero"`

	// maxThreadsPerSM / warpSize
	MaxWarpsPerSM *int `json:"maxWarpsPerSM,omitempty,omitzero"`

	// streaming multiprocessors
	SMs *int `json:"sms,omitempty,omitzero"`

	// WarpSize corresponds to the JSON schema field "warpSize".
	WarpSize *int `json:"warpSize,omitempty,omitzero"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Layout) UnmarshalJSON(value []byte) error {
	type Plain Layout
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.MaxBlockDim != nil && len(plain.MaxBlockDim) < 3 {
		return fmt.Errorf("field %s length: must be >= %d", "maxBlockDim", 3)
	}
	if len(plain.MaxBlockDim) > 3 {
		return fmt.Errorf("field %s length: must be <= %d", "maxBlockDim", 3)
	}
	if plain.MaxGridDim != nil && len(plain.MaxGridDim) < 3 {
		return fmt.Errorf("field %s length: must be >= %d", "maxGridDim", 3)
	}
	if len(plain.MaxGridDim) > 3 {
		return fmt.Errorf("field %s length: must be <= %d", "maxGridDim", 3)
	}
	*j = Layout(plain)
	return nil
}

type Limit string

const LimitApplicationsClocks Limit = "applications_clocks"
const LimitDisplayClocks Limit = "display_clocks"
const LimitGPUIdle Limit = "gpu_idle"
const LimitHwPowerBrake Limit = "hw_power_brake"
const LimitHwSlowdown Limit = "hw_slowdown"
const LimitHwThermal Limit = "hw_thermal"
const LimitSwPowerCap Limit = "sw_power_cap"
const LimitSwThermal Limit = "sw_thermal"
const LimitSyncBoost Limit = "sync_boost"

var enumValues_Limit = []interface{}{
	"gpu_idle",
	"applications_clocks",
	"sw_power_cap",
	"hw_slowdown",
	"sync_boost",
	"sw_thermal",
	"hw_thermal",
	"hw_power_brake",
	"display_clocks",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Limit) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Limit {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Limit, v)
	}
	*j = Limit(v)
	return nil
}

type List interface{}

// Every card the kernel bound; lost ones are cards with state lost, not a failure.
type ListOK struct {
	// Cards corresponds to the JSON schema field "cards".
	Cards []Card `json:"cards"`

	// highest CUDA version the driver supports, "13.1"
	CUDA *string `json:"cuda,omitempty,omitzero"`

	// kernel module version from /proc, "590.48.01"; empty when unreadable
	Driver string `json:"driver"`

	// NVML could not be used; every card's state is unknown
	Error *ErrorBody `json:"error,omitempty,omitzero"`

	// NVML library version
	NVML *string `json:"nvml,omitempty,omitzero"`

	// NVQ corresponds to the JSON schema field "nvq".
	NVQ SchemaVersion `json:"nvq"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ListOK) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["cards"]; raw != nil && !ok {
		return fmt.Errorf("field cards in ListOK: required")
	}
	if _, ok := raw["driver"]; raw != nil && !ok {
		return fmt.Errorf("field driver in ListOK: required")
	}
	if _, ok := raw["nvq"]; raw != nil && !ok {
		return fmt.Errorf("field nvq in ListOK: required")
	}
	type Plain ListOK
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ListOK(plain)
	return nil
}

// milliseconds per step, in the order run
type MS map[string]float64

type Memory struct {
	// BusWidthBits corresponds to the JSON schema field "busWidthBits".
	BusWidthBits *int `json:"busWidthBits,omitempty,omitzero"`

	// ClockMHz corresponds to the JSON schema field "clockMHz".
	ClockMHz *int `json:"clockMHz,omitempty,omitzero"`

	// ConstantBytes corresponds to the JSON schema field "constantBytes".
	ConstantBytes *int `json:"constantBytes,omitempty,omitzero"`

	// L2Bytes corresponds to the JSON schema field "l2Bytes".
	L2Bytes *int `json:"l2Bytes,omitempty,omitzero"`

	// L2PersistingBytes corresponds to the JSON schema field "l2PersistingBytes".
	L2PersistingBytes *int `json:"l2PersistingBytes,omitempty,omitzero"`

	// clockMHz × 2 (double data rate) × busWidthBits / 8, in GB/s
	PeakGBs *float64 `json:"peakGBs,omitempty,omitzero"`

	// TotalMiB corresponds to the JSON schema field "totalMiB".
	TotalMiB int `json:"totalMiB"`
}

type MemoryMiB struct {
	// Total corresponds to the JSON schema field "total".
	Total int `json:"total"`

	// Used corresponds to the JSON schema field "used".
	Used int `json:"used"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MemoryMiB) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["total"]; raw != nil && !ok {
		return fmt.Errorf("field total in MemoryMiB: required")
	}
	if _, ok := raw["used"]; raw != nil && !ok {
		return fmt.Errorf("field used in MemoryMiB: required")
	}
	type Plain MemoryMiB
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = MemoryMiB(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Memory) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["totalMiB"]; raw != nil && !ok {
		return fmt.Errorf("field totalMiB in Memory: required")
	}
	type Plain Memory
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Memory(plain)
	return nil
}

// the link now and at best; a riser shows here (gen 1, width 1)
type PCIe struct {
	// Gen corresponds to the JSON schema field "gen".
	Gen int `json:"gen"`

	// MaxGen corresponds to the JSON schema field "maxGen".
	MaxGen int `json:"maxGen"`

	// MaxWidth corresponds to the JSON schema field "maxWidth".
	MaxWidth int `json:"maxWidth"`

	// link-level retransmissions since the driver loaded; one that keeps rising is a
	// failing riser or slot
	Replays *int `json:"replays,omitempty,omitzero"`

	// Width corresponds to the JSON schema field "width".
	Width int `json:"width"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PCIe) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["gen"]; raw != nil && !ok {
		return fmt.Errorf("field gen in PCIe: required")
	}
	if _, ok := raw["maxGen"]; raw != nil && !ok {
		return fmt.Errorf("field maxGen in PCIe: required")
	}
	if _, ok := raw["maxWidth"]; raw != nil && !ok {
		return fmt.Errorf("field maxWidth in PCIe: required")
	}
	if _, ok := raw["width"]; raw != nil && !ok {
		return fmt.Errorf("field width in PCIe: required")
	}
	type Plain PCIe
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = PCIe(plain)
	return nil
}

type PowerW struct {
	// Draw corresponds to the JSON schema field "draw".
	Draw *float64 `json:"draw,omitempty,omitzero"`

	// enforced limit
	Limit *float64 `json:"limit,omitempty,omitzero"`
}

type Probe interface{}

type ProbeAll interface{}

// One entry per card, each naming its card; a card that failed is an entry that
// says how, not a failure.
type ProbeAllOK struct {
	// NVQ corresponds to the JSON schema field "nvq".
	NVQ SchemaVersion `json:"nvq"`

	// Probes corresponds to the JSON schema field "probes".
	Probes []interface{} `json:"probes"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ProbeAllOK) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["nvq"]; raw != nil && !ok {
		return fmt.Errorf("field nvq in ProbeAllOK: required")
	}
	if _, ok := raw["probes"]; raw != nil && !ok {
		return fmt.Errorf("field probes in ProbeAllOK: required")
	}
	type Plain ProbeAllOK
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ProbeAllOK(plain)
	return nil
}

type ProbeFailed struct {
	// a CUDA_ERROR_* name, or not_visible, more_than_one_visible, uuid_mismatch,
	// no_compute_capability, wrong_result, library_not_found, function_not_found:
	// <name>; in probe all also deadline (the child's own deadline ended an
	// interruptible call), killed_at_deadline, stuck_in_driver, no_output
	Error string `json:"error"`

	// crash: the child's exit code
	Exit *int `json:"exit,omitempty,omitzero"`

	// MS corresponds to the JSON schema field "ms".
	MS MS `json:"ms,omitempty,omitzero"`

	// NVQ corresponds to the JSON schema field "nvq".
	NVQ SchemaVersion `json:"nvq"`

	// OK corresponds to the JSON schema field "ok".
	OK bool `json:"ok"`

	// stuck_in_driver: the child that could not be reaped
	PID *int `json:"pid,omitempty,omitzero"`

	// crash: the signal that ended the child
	Signal *int `json:"signal,omitempty,omitzero"`

	// load, init, device, uuid, name, memory, driver, attributes, context, alloc,
	// memset, jit, function, launch, sync, copy, verify, free, unload, teardown; in
	// probe all also hang (killed or stuck) and crash (died without a document)
	Step string `json:"step"`

	// UUID corresponds to the JSON schema field "uuid".
	UUID UUID `json:"uuid"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ProbeFailed) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["error"]; raw != nil && !ok {
		return fmt.Errorf("field error in ProbeFailed: required")
	}
	if _, ok := raw["nvq"]; raw != nil && !ok {
		return fmt.Errorf("field nvq in ProbeFailed: required")
	}
	if _, ok := raw["ok"]; raw != nil && !ok {
		return fmt.Errorf("field ok in ProbeFailed: required")
	}
	if _, ok := raw["step"]; raw != nil && !ok {
		return fmt.Errorf("field step in ProbeFailed: required")
	}
	if _, ok := raw["uuid"]; raw != nil && !ok {
		return fmt.Errorf("field uuid in ProbeFailed: required")
	}
	type Plain ProbeFailed
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.OK != false {
		return fmt.Errorf("field %s: must be equal to %t", "ok", false)
	}
	*j = ProbeFailed(plain)
	return nil
}

type ProbeOK struct {
	// Arch corresponds to the JSON schema field "arch".
	Arch Arch `json:"arch"`

	// ComputeMode corresponds to the JSON schema field "computeMode".
	ComputeMode *ComputeMode `json:"computeMode,omitempty,omitzero"`

	// ConcurrentKernels corresponds to the JSON schema field "concurrentKernels".
	ConcurrentKernels *bool `json:"concurrentKernels,omitempty,omitzero"`

	// copies that can overlap a kernel
	CopyEngines *int `json:"copyEngines,omitempty,omitzero"`

	// CUDA driver API version, "13.1"
	CUDA string `json:"cuda"`

	// ECC corresponds to the JSON schema field "ecc".
	ECC *bool `json:"ecc,omitempty,omitzero"`

	// Integrated corresponds to the JSON schema field "integrated".
	Integrated *bool `json:"integrated,omitempty,omitzero"`

	// Layout corresponds to the JSON schema field "layout".
	Layout Layout `json:"layout"`

	// Memory corresponds to the JSON schema field "memory".
	Memory Memory `json:"memory"`

	// MS corresponds to the JSON schema field "ms".
	MS MS `json:"ms"`

	// MultiGPUBoard corresponds to the JSON schema field "multiGpuBoard".
	MultiGPUBoard *bool `json:"multiGpuBoard,omitempty,omitzero"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// NVQ corresponds to the JSON schema field "nvq".
	NVQ SchemaVersion `json:"nvq"`

	// OK corresponds to the JSON schema field "ok".
	OK bool `json:"ok"`

	// Registers corresponds to the JSON schema field "registers".
	Registers Registers `json:"registers"`

	// SharedBytes corresponds to the JSON schema field "sharedBytes".
	SharedBytes SharedBytes `json:"sharedBytes"`

	// the SM's peak clock
	SMClockMHz *int `json:"smClockMHz,omitempty,omitzero"`

	// attributes the driver did not report
	Unsupported []string `json:"unsupported,omitempty,omitzero"`

	// UUID corresponds to the JSON schema field "uuid".
	UUID UUID `json:"uuid"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ProbeOK) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["arch"]; raw != nil && !ok {
		return fmt.Errorf("field arch in ProbeOK: required")
	}
	if _, ok := raw["cuda"]; raw != nil && !ok {
		return fmt.Errorf("field cuda in ProbeOK: required")
	}
	if _, ok := raw["layout"]; raw != nil && !ok {
		return fmt.Errorf("field layout in ProbeOK: required")
	}
	if _, ok := raw["memory"]; raw != nil && !ok {
		return fmt.Errorf("field memory in ProbeOK: required")
	}
	if _, ok := raw["ms"]; raw != nil && !ok {
		return fmt.Errorf("field ms in ProbeOK: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in ProbeOK: required")
	}
	if _, ok := raw["nvq"]; raw != nil && !ok {
		return fmt.Errorf("field nvq in ProbeOK: required")
	}
	if _, ok := raw["ok"]; raw != nil && !ok {
		return fmt.Errorf("field ok in ProbeOK: required")
	}
	if _, ok := raw["registers"]; raw != nil && !ok {
		return fmt.Errorf("field registers in ProbeOK: required")
	}
	if _, ok := raw["sharedBytes"]; raw != nil && !ok {
		return fmt.Errorf("field sharedBytes in ProbeOK: required")
	}
	if _, ok := raw["uuid"]; raw != nil && !ok {
		return fmt.Errorf("field uuid in ProbeOK: required")
	}
	type Plain ProbeOK
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.OK != true {
		return fmt.Errorf("field %s: must be equal to %t", "ok", true)
	}
	*j = ProbeOK(plain)
	return nil
}

type Process struct {
	// PID corresponds to the JSON schema field "pid".
	PID int `json:"pid"`

	// absent when NVML cannot see it (another container)
	UsedMiB *int `json:"usedMiB,omitempty,omitzero"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Process) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["pid"]; raw != nil && !ok {
		return fmt.Errorf("field pid in Process: required")
	}
	type Plain Process
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Process(plain)
	return nil
}

type Registers struct {
	// PerBlock corresponds to the JSON schema field "perBlock".
	PerBlock *int `json:"perBlock,omitempty,omitzero"`

	// PerSM corresponds to the JSON schema field "perSM".
	PerSM *int `json:"perSM,omitempty,omitzero"`
}

type SchemaVersion int

// UnmarshalJSON implements json.Unmarshaler.
func (j *SchemaVersion) UnmarshalJSON(value []byte) error {
	type Plain SchemaVersion
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain != 1 {
		return fmt.Errorf("field %s: must be equal to %v", "", 1)
	}
	*j = SchemaVersion(plain)
	return nil
}

type SharedBytes struct {
	// without opting in
	PerBlock *int `json:"perBlock,omitempty,omitzero"`

	// the most a kernel may request with cuFuncSetAttribute
	PerBlockOptin *int `json:"perBlockOptin,omitempty,omitzero"`

	// PerSM corresponds to the JSON schema field "perSM".
	PerSM *int `json:"perSM,omitempty,omitzero"`
}

type State string

const StateError State = "error"
const StateLost State = "lost"
const StateOK State = "ok"
const StateUnknown State = "unknown"

var enumValues_State = []interface{}{
	"ok",
	"lost",
	"error",
	"unknown",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *State) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_State {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_State, v)
	}
	*j = State(v)
	return nil
}

type UUID string

// UnmarshalJSON implements json.Unmarshaler.
func (j *UUID) UnmarshalJSON(value []byte) error {
	type Plain UUID
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^GPU-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^GPU-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`)
	}
	*j = UUID(plain)
	return nil
}

// seconds since the epoch, millisecond precision
type UnixTime float64

type UtilPct struct {
	// GPU corresponds to the JSON schema field "gpu".
	GPU int `json:"gpu"`

	// Mem corresponds to the JSON schema field "mem".
	Mem int `json:"mem"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UtilPct) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["gpu"]; raw != nil && !ok {
		return fmt.Errorf("field gpu in UtilPct: required")
	}
	if _, ok := raw["mem"]; raw != nil && !ok {
		return fmt.Errorf("field mem in UtilPct: required")
	}
	type Plain UtilPct
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = UtilPct(plain)
	return nil
}

type Version struct {
	// NVQ corresponds to the JSON schema field "nvq".
	NVQ SchemaVersion `json:"nvq"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Version) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["nvq"]; raw != nil && !ok {
		return fmt.Errorf("field nvq in Version: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in Version: required")
	}
	type Plain Version
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Version(plain)
	return nil
}

type WatchCard struct {
	// Bus corresponds to the JSON schema field "bus".
	Bus Bus `json:"bus"`

	// Error corresponds to the JSON schema field "error".
	Error *Code `json:"error,omitempty,omitzero"`

	// event kinds registered for this card
	Events []EventsEvent `json:"events,omitempty,omitzero"`

	// EventsError corresponds to the JSON schema field "eventsError".
	EventsError *Code `json:"eventsError,omitempty,omitzero"`

	// State corresponds to the JSON schema field "state".
	State WatchCardState `json:"state"`

	// UUID corresponds to the JSON schema field "uuid".
	UUID UUID `json:"uuid"`
}

type WatchCardState string

const WatchCardStateError WatchCardState = "error"
const WatchCardStateLost WatchCardState = "lost"
const WatchCardStateOK WatchCardState = "ok"

var enumValues_WatchCardState = []interface{}{
	"ok",
	"lost",
	"error",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WatchCardState) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_WatchCardState {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_WatchCardState, v)
	}
	*j = WatchCardState(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WatchCard) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["bus"]; raw != nil && !ok {
		return fmt.Errorf("field bus in WatchCard: required")
	}
	if _, ok := raw["state"]; raw != nil && !ok {
		return fmt.Errorf("field state in WatchCard: required")
	}
	if _, ok := raw["uuid"]; raw != nil && !ok {
		return fmt.Errorf("field uuid in WatchCard: required")
	}
	type Plain WatchCard
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = WatchCard(plain)
	return nil
}
