# generated by datamodel-codegen:
#   filename:  nvq.schema.json

from __future__ import annotations
from typing import Any, Literal, NotRequired, TypedDict


type Nvq = Any
"""
NVIDIA cards as JSON. Every document carries "nvq": 1, the version of this schema; additive fields keep it, a removal or a change of meaning bumps it. Readers ignore keys they do not know. A value the card cannot report is absent, never zero, and named under "unsupported".
"""


type SchemaVersion = Literal[1]


type Uuid = str


type Bus = str
"""
PCI location as the kernel prints it
"""


type UnixTime = float
"""
seconds since the epoch, millisecond precision
"""


type Code = Literal[
    "uninitialized",
    "invalid_argument",
    "not_supported",
    "no_permission",
    "already_initialized",
    "not_found",
    "insufficient_size",
    "insufficient_power",
    "driver_not_loaded",
    "timeout",
    "irq_issue",
    "library_not_found",
    "function_not_found",
    "corrupted_inforom",
    "gpu_is_lost",
    "reset_required",
    "operating_system",
    "lib_rm_version_mismatch",
    "in_use",
    "memory",
    "no_data",
    "vgpu_ecc_not_supported",
    "insufficient_resources",
    "freq_not_supported",
    "argument_version_mismatch",
    "deprecated",
    "not_ready",
    "gpu_not_found",
    "invalid_state",
    "unknown",
    "too_many_cards",
    "deadline",
]
"""
Why something failed: NVML's return codes by name, plus nvq's own.
"""


class ErrorBody(TypedDict):
    code: Code
    detail: str


type Limit = Literal[
    "gpu_idle",
    "applications_clocks",
    "sw_power_cap",
    "hw_slowdown",
    "sync_boost",
    "sw_thermal",
    "hw_thermal",
    "hw_power_brake",
    "display_clocks",
]
"""
Why the card's clocks are below their maximum right now (NVML clock event reasons).
"""


class MemoryMiB(TypedDict):
    total: int
    used: int


class PowerW(TypedDict):
    limit: NotRequired[float]
    """
    enforced limit
    """
    draw: NotRequired[float]


class ClocksMHz(TypedDict):
    sm: int
    mem: int


class UtilPct(TypedDict):
    gpu: int
    mem: int


class Pcie(TypedDict):
    """
    the link now and at best; a riser shows here (gen 1, width 1)
    """

    gen: int
    width: int
    maxGen: int
    maxWidth: int
    replays: NotRequired[int]
    """
    link-level retransmissions since the driver loaded; one that keeps rising is a failing riser or slot
    """


class Process(TypedDict):
    pid: int
    usedMiB: NotRequired[int]
    """
    absent when NVML cannot see it (another container)
    """


class Card(TypedDict):
    index: int
    """
    position in bus order; not CUDA's or nvidia-smi's index
    """
    uuid: Uuid
    bus: Bus
    minor: int
    """
    /dev/nvidia<minor>; -1 when the kernel did not say
    """
    model: str
    state: Literal["ok", "lost", "error", "unknown"]
    """
    ok: NVML reaches it. lost: fell off the bus (gpu_is_lost). error: another NVML failure. unknown: NVML unusable
    """
    error: NotRequired[Code]
    """
    with state lost or error
    """
    compute: NotRequired[str]
    """
    CUDA compute capability, "8.6"
    """
    memoryMiB: NotRequired[MemoryMiB]
    powerW: NotRequired[PowerW]
    tempC: NotRequired[int]
    fanPct: NotRequired[int]
    """
    target fan speed; consumer cards with fan control off report not_supported
    """
    clocksMHz: NotRequired[ClocksMHz]
    utilPct: NotRequired[UtilPct]
    pstate: NotRequired[int]
    """
    performance state, 0 fastest
    """
    pcie: NotRequired[Pcie]
    """
    the link now and at best; a riser shows here (gen 1, width 1)
    """
    energyJ: NotRequired[float]
    """
    energy the card used since the driver loaded, joules; the difference of two readings over their interval is average power
    """
    persistence: NotRequired[bool]
    limits: NotRequired[list[Limit]]
    processes: NotRequired[list[Process]]
    """
    compute processes holding the card
    """
    unsupported: NotRequired[list[str]]
    """
    fields this card does not report
    """
    errors: NotRequired[dict[str, Code]]
    """
    fields whose query failed, by field
    """


type Ms = dict[str, float]
"""
milliseconds per step, in the order run
"""


class ProbeFailed(TypedDict):
    nvq: SchemaVersion
    uuid: Uuid
    ok: Literal[False]
    step: str
    """
    load, init, device, uuid, name, memory, driver, attributes, context, alloc, memset, jit, function, launch, sync, copy, verify, free, unload, teardown; in probe all also hang (killed or stuck) and crash (died without a document)
    """
    error: str
    """
    a CUDA_ERROR_* name, or not_visible, more_than_one_visible, uuid_mismatch, no_compute_capability, wrong_result, library_not_found, function_not_found: <name>, killed_at_deadline, stuck_in_driver, no_output
    """
    ms: NotRequired[Ms]
    signal: NotRequired[int]
    """
    crash: the signal that ended the child
    """
    exit: NotRequired[int]
    """
    crash: the child's exit code
    """
    pid: NotRequired[int]
    """
    stuck_in_driver: the child that could not be reaped
    """


class Arch(TypedDict):
    compute: str
    """
    "8.6"
    """
    sm: str
    """
    the compile target, "sm_86"
    """
    family: Literal[
        "kepler", "maxwell", "pascal", "volta", "turing", "ampere", "ada", "hopper", "blackwell", "unknown"
    ]


class Layout(TypedDict):
    sms: NotRequired[int]
    """
    streaming multiprocessors
    """
    warpSize: NotRequired[int]
    maxThreadsPerBlock: NotRequired[int]
    maxThreadsPerSM: NotRequired[int]
    maxBlocksPerSM: NotRequired[int]
    maxWarpsPerSM: NotRequired[int]
    """
    maxThreadsPerSM / warpSize
    """
    maxBlockDim: NotRequired[list[int]]
    maxGridDim: NotRequired[list[int]]


class Registers(TypedDict):
    perBlock: NotRequired[int]
    perSM: NotRequired[int]


class SharedBytes(TypedDict):
    perBlock: NotRequired[int]
    """
    without opting in
    """
    perBlockOptin: NotRequired[int]
    """
    the most a kernel may request with cuFuncSetAttribute
    """
    perSM: NotRequired[int]


class Memory(TypedDict):
    totalMiB: int
    busWidthBits: NotRequired[int]
    clockMHz: NotRequired[int]
    peakGBs: NotRequired[float]
    """
    clockMHz × 2 (double data rate) × busWidthBits / 8, in GB/s
    """
    l2Bytes: NotRequired[int]
    l2PersistingBytes: NotRequired[int]
    constantBytes: NotRequired[int]


class ProbeOk(TypedDict):
    nvq: SchemaVersion
    uuid: Uuid
    ok: Literal[True]
    name: str
    cuda: str
    """
    CUDA driver API version, "13.1"
    """
    arch: Arch
    layout: Layout
    registers: Registers
    sharedBytes: SharedBytes
    memory: Memory
    smClockMHz: NotRequired[int]
    """
    the SM's peak clock
    """
    copyEngines: NotRequired[int]
    """
    copies that can overlap a kernel
    """
    concurrentKernels: NotRequired[bool]
    computeMode: NotRequired[Literal["default", "prohibited", "exclusive_process", "unknown"]]
    ecc: NotRequired[bool]
    integrated: NotRequired[bool]
    multiGpuBoard: NotRequired[bool]
    unsupported: NotRequired[list[str]]
    """
    attributes the driver did not report
    """
    ms: Ms


class WatchCard(TypedDict):
    uuid: Uuid
    bus: Bus
    state: Literal["ok", "lost", "error"]
    error: NotRequired[Code]
    events: NotRequired[list[Literal["xid", "ecc_double"]]]
    """
    event kinds registered for this card
    """
    eventsError: NotRequired[Code]


class EventXid(TypedDict):
    """
    An Xid error the driver raised; uuid and bus absent when NVML named a device nvq does not watch.
    """

    nvq: SchemaVersion
    event: Literal["xid"]
    at: UnixTime
    uuid: NotRequired[Uuid]
    bus: NotRequired[Bus]
    xid: int
    meaning: str
    """
    NVIDIA's name for it; empty for an Xid nvq has no name for
    """


class EventEccDouble(TypedDict):
    """
    A double-bit ECC error; uuid and bus absent when NVML named a device nvq does not watch.
    """

    nvq: SchemaVersion
    event: Literal["ecc_double"]
    at: UnixTime
    uuid: NotRequired[Uuid]
    bus: NotRequired[Bus]
    data: int


class EventLost(TypedDict):
    """
    A card NVML stopped reaching, reported once.
    """

    nvq: SchemaVersion
    event: Literal["lost"]
    at: UnixTime
    uuid: Uuid
    bus: Bus
    error: Code


class EventWaitError(TypedDict):
    """
    Waiting for driver events failed; watch retries after a second.
    """

    nvq: SchemaVersion
    event: Literal["wait_error"]
    at: UnixTime
    error: Code


class EventSample(TypedDict):
    """
    One card's readings, every --every-ms; a reading the card cannot give is absent.
    """

    nvq: SchemaVersion
    event: Literal["sample"]
    at: UnixTime
    uuid: Uuid
    bus: Bus
    tempC: NotRequired[int]
    powerW: NotRequired[float]
    smMHz: NotRequired[int]
    utilPct: NotRequired[int]
    fanPct: NotRequired[int]
    energyJ: NotRequired[float]
    """
    cumulative, as in list
    """
    pcieReplays: NotRequired[int]
    """
    cumulative, as in list
    """
    limits: NotRequired[list[Limit]]


class Version(TypedDict):
    nvq: SchemaVersion
    version: str


class Error(TypedDict):
    """
    The whole command failed, or (in list) NVML could not be used.
    """

    nvq: SchemaVersion
    error: ErrorBody


class ListOk(TypedDict):
    """
    Every card the kernel bound; lost ones are cards with state lost, not a failure.
    """

    nvq: SchemaVersion
    driver: str
    """
    kernel module version from /proc, "590.48.01"; empty when unreadable
    """
    nvml: NotRequired[str]
    """
    NVML library version
    """
    cuda: NotRequired[str]
    """
    highest CUDA version the driver supports, "13.1"
    """
    error: NotRequired[ErrorBody]
    """
    NVML could not be used; every card's state is unknown
    """
    cards: list[Card]


type Probe = Error | ProbeOk | ProbeFailed


class ProbeAllOk(TypedDict):
    """
    One entry per card; a card that failed is an entry that says how, not a failure.
    """

    nvq: SchemaVersion
    probes: list[Error | ProbeOk | ProbeFailed]


class EventStart(TypedDict):
    """
    First line: the cards watched and the event kinds registered on each.
    """

    nvq: SchemaVersion
    event: Literal["start"]
    at: UnixTime
    cards: list[WatchCard]


type List = Error | ListOk


type ProbeAll = Error | ProbeAllOk


type Event = Error | EventStart | EventXid | EventEccDouble | EventLost | EventWaitError | EventSample
"""
One line of watch, told apart by "event".
"""
